### ISSUE TITLE
add Show in sidebar like other plugins

### ISSUE THREAD

**Issue by lilbuh** [hassio-addons/addon-tautulli#61] opened 2020-06-04 10:23 UTC
# Problem/Motivation
before using homeassistant from outside my house i used to add 

panel_iframe:
  tautulli:
    title: 'Tautulli'
    url: 'http://192.168.1.100:8181'
    icon: mdi:plex

to my config and worked alright
but now since i m always acessing it from my duckdns address it doesn t work anymore
i COULD open another port and forward it but id rather not

## Proposed changes

do like some other plugins like ESPHOME wich works even without forwarding ports

**Comment by sinclairpaul** [comment] 2020-06-04 12:58
Duplicate of #54 

Not all applications can support the functionality.

**Closed by sinclairpaul** 2020-06-04 12:58 UTC
