### ISSUE TITLE
https not working after 1.4.0 update

### ISSUE THREAD

**Issue by MrUkleja** [hassio-addons/addon-tautulli#53] opened 2020-01-09 22:10 UTC
# Problem/Motivation

After latest upgrade to 1.4.0, https connection stopped to work. Http is working ok, bit since I'm accessing my hassio using https, I lost access to tautulli via iframe panel

## Expected behavior

Access via https should work as previously configured

## Actual behavior

I'm getting error in the browser:
ERR_SSL_PROTOCOL_ERROR

Also error in add-on log:
2020-01-09 22:45:24 - WARNING :: MainThread : The pyOpenSSL module is missing. Install this module to enable HTTPS. HTTPS will be disabled.

Also, inside add-on in Settings section, https is not checked. After turning it on and restarting it is still unchecked.

## Steps to reproduce

Try to access add-on via https
My config didn't change:

> {

  "username": "my username",
  "password": "my password",
  "ssl": true,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "log_level": "info"
}

**Comment by 1MRB** [comment] 2020-01-10 00:39
If it helps i am also getting the error below for https requests after migrating to 1.4.0

Secure Connection Failed
An error occurred during a connection to xxxxx.xxxxx.com:8181. SSL received a record that exceeded the maximum permissible length.
Error code: SSL_ERROR_RX_RECORD_TOO_LONG

**Comment by dreimer1986** [comment] 2020-01-11 10:25
Confirmed: LOG: https://www.pastiebin.com/5e19a23f26b49
"The pyOpenSSL module is missing. Install this module to enable HTTPS. HTTPS will be disabled."
Config reset to default, aka username and password added and rest is addin default aka SSL active.

**Comment by rpitera** [comment] 2020-01-11 15:44
Same here; thought I did something wrong.  Is there any way to roll back to the last version?

**Comment by Kedryn** [comment] 2020-01-16 12:07
here too

2020-01-16 12:58:56 - WARNING :: MainThread : The pyOpenSSL module is missing. Install this module to enable HTTPS. HTTPS will be disabled.

**Comment by nightops** [comment] 2020-01-21 19:24
Same issue on trying to open Tautulli running via Hassio on an RPi 4

**Comment by rpitera** [comment] 2020-01-25 15:06
At least once a day I go to my hass.io page hoping to see that update icon on Tautulli... and then the sadness grips me...  : (

**Comment by rpitera** [comment] 2020-01-29 23:24
Is more information needed?  Is there something we need to provide on our end to move closer to closing this issue?  Just wondering and volunteering if there is anything I can do.

**Comment by sinclairpaul** [comment] 2020-01-29 23:32
Unless you can upgrade the app to Python 3.0, at this time nope 😄

**Comment by rpitera** [comment] 2020-01-30 14:38
Paul, can you clarify?  What changed between this and the last version?  Tautulli?  openSSL?  I'm naive in the ways of Docker containers and add ons.

**Comment by sinclairpaul** [comment] 2020-01-30 14:47
From the investigation I did, I believe it is likely this:

https://github.com/hassio-addons/addon-tautulli/commit/7259691704d4297715c8e05ddce2893358b3a928

Which looks like it is a Python 3 version of the library, the 2 library is no longer available for Alpine 3.11.  Considering Python 2 is no longer supported these issues would likely only increase.

I could be wrong (its a likely possibility 😉 ), but I do think supporting Python 2 apps should really be a no go at this point in time.

**Comment by rpitera** [comment] 2020-01-30 15:29
Thanks, that really helped me to understand it better.  Looking at Tautulli's repo it looks like a PR was put in for Py3 support but closed without comment so I guess Tautulli, at least as an Add On for HA is dead.  Bummer.

**Comment by davveh** [comment] 2020-02-14 15:43
Could maybe build this addon on this instead:
https://github.com/zSeriesGuy/Tautulli

Yes its a fork and it will probably not be migrated but still, its python3 atleast and would solve alot.

How do you guys manage today? Not that its not working properly..

**Comment by rpitera** [comment] 2020-02-14 17:08
I built a bunch of sensors using the REST api and calling it locally with http.  

```
#
# Tautulli REST sensors
#

- platform: rest
  name: plex library tables
  resource: !secret plex_library_tables_resource
  json_attributes:
    - response
  value_template: '{{ value_json.response.result }}'
  scan_interval: 60

- platform: rest
  name: plex libraries
  resource: !secret plex_libraries_resource
  json_attributes:
    - response
  value_template: '{{ value_json.response.result }}'
  scan_interval: 60
```

My resources look like this:

```
plex_library_tables_resource: 'http://LOCAL_HA_IP:8181/api/v2?apikey=YOURTAUTULLIAPIKEY&cmd=get_libraries_table'

plex_libraries_resource: 'http://LOCAL_HA_IP:8181/api/v2?apikey=YOURTAUTULLIAPIKEY&cmd=get_libraries'
```

Then I used templates to build sensors out the attributes I was interested in and made cards for them using Thomas Loven's template-entity-row and styled them using card-mod.

Yeah, it was the long way round, but I learned a lot in the process and I like the way the cards look so in the meantime this is working well for me.

**Comment by frenck** [comment] 2020-02-25 20:56
Fixed in dev.

**Closed** 2020-02-25 20:56 UTC
Labels: Type: Bug
